### ISSUE TITLE
Ignored variables

### ISSUE THREAD

**Issue by fiddlerwoaroof** [hoverinc/hover-javascript#306]
Maybe add a rule to allow unused variables or arguments that begin with an underscore? This is colored by my experience with Clojure, but I find something like this a nice convention when you don't care about an argument:

```
doThing((_, it) => it+1, ...)
```

Or even this: 

```
doThing(_ => whatever(), ...)
````

**Comment by jrolfs** [comment]
I believe this should work fine as configured... I use this all the time and the projects I work in all use **@hover/javascript**.
